Repository puppetlabs/puppetlabs-dsc_lite, pull requests merged in 2024-05, with the labels that each got.

#207 (CAT-1776) Implement reusable workflows
  .github/workflows/auto_release.yml
  .github/workflows/labeller.yml
  .github/workflows/mend.yml
  .github/workflows/release_prep.yml
  .github/workflows/spec.yml
  .github/workflows/stale.yml
  .sync.yml
Labels: maintenance

#204 Fix ERB.new depracation notices
  lib/puppet/provider/base_dsc_lite/powershell.rb
Labels: bugfix, community

#208 (IT-87329) - Update workflows to run on pull_request
  .github/workflows/mend.yml
Labels: maintenance

#209 (CAT-1861) Puppet 8 upgrade / Drop Puppet 6 support
  .gitignore
  .pdkignore
  .rubocop.yml
  .rubocop_todo.yml
  Gemfile
  lib/puppet/provider/base_dsc_lite/powershell.rb
  lib/puppet/type/dsc.rb
  lib/puppet_x/puppetlabs/dsc_lite/dsc_type_helpers.rb
  lib/puppet_x/puppetlabs/dsc_lite/powershell_hash_formatter.rb
  metadata.json
  spec/acceptance/basic_dsc_resources/failing_dsc_resources_spec.rb
  spec/acceptance/basic_functionality/puppet_apply_dsc_manifest_spec.rb
  spec/acceptance/dsc_type/multiple_dsc_resources_in_psmodulepath_spec.rb
  spec/acceptance/reboot/reboot_no_invoke_warning_spec.rb
  spec/lib/dsc_utils.rb
  spec/spec_helper.rb
  spec/spec_helper_acceptance.rb
  spec/spec_helper_acceptance_local.rb
  spec/unit/puppet/type/base_dsc_spec.rb
  spec/unit/puppet/type/dsc_spec.rb
  spec/unit/puppet_x/dsc_lite/powershell_hash_formatter_spec.rb
Labels: backwards-incompatible
