Repository puppetlabs/puppetlabs-dsc_lite, pull requests merged in 2024-06, with the labels that each got.

#211 (bug) - Update readme for release on forge
  README.md
Labels: bugfix

#213 (CAT-1869) - Add configurable dsc_timeout param for dsc type
  .rubocop_todo.yml
  REFERENCE.md
  lib/puppet/provider/base_dsc_lite/powershell.rb
  lib/puppet/type/dsc.rb
  spec/acceptance/dsc_type/psdesiredstateconfiguration_spec.rb
Labels: feature

#214 (maint) - Implement retries for timeout test
  spec/acceptance/dsc_type/psdesiredstateconfiguration_spec.rb
  spec/spec_helper_acceptance_local.rb
Labels: maintenance

#215 (maint) Update labeller.yml to pull_request
  .github/workflows/labeller.yml
Labels: maintenance

#216 Revert "(maint) Update labeller.yml to pull_request"
  .github/workflows/labeller.yml
Labels: maintenance
